# Generated by Django 4.2.23 on 2025-09-15 08:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feeaccount_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdconfig',
            name='name',
            field=models.CharField(default='default', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ussdconfig',
            name='menu_json',
            field=models.JSONField(blank=True, default=dict, validators=[core.models.validate_menu_json]),
        ),
    ]
