# Generated by Django 4.2.24 on 2025-09-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grade_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
