# Generated by Django 4.2.24 on 2025-09-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_message_student_remove_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='target_audience',
            field=models.CharField(default='all', max_length=64),
        ),
    ]
