# Generated by Django 4.2.23 on 2025-09-19 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ussdconfig_name_alter_ussdconfig_menu_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('recipient_type', models.CharField(default='all', max_length=64)),
                ('recipient_filter', models.JSONField(blank=True, null=True)),
                ('recipient_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_stats', models.JSONField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='attendance_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='term',
            field=models.CharField(default='Term 1', max_length=32),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='weeks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeaccount',
            name='currency',
            field=models.CharField(default='KES', max_length=8),
        ),
        migrations.AddField(
            model_name='feeaccount',
            name='next_payment_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='results/'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='term',
            field=models.CharField(default='Term 1', max_length=32),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='Active', max_length=32),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='grade',
            field=models.CharField(max_length=8),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_email', models.EmailField(max_length=254)),
                ('concern_type', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('request_callback', models.BooleanField(default=False)),
                ('schedule_meeting', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='new', max_length=32)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
    ]
